"""Add QR code to certificate

Revision ID: 851ddc4c18f3
Revises: cbb6ac363d5d
Create Date: 2025-11-25 11:33:49.632006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851ddc4c18f3'
down_revision = 'cbb6ac363d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('qr_code_url')

    # ### end Alembic commands ###
