"""Add timestamps and update certificate model

Revision ID: e0b6c8938119
Revises: 851ddc4c18f3
Create Date: 2025-11-25 11:57:26.704676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0b6c8938119'
down_revision = '851ddc4c18f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('student_last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('course_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=20), nullable=True))
        batch_op.alter_column('verification_code',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('pdf_url')
        batch_op.drop_column('is_active')
        batch_op.drop_column('student_name')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('verification_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('course_summary')
        batch_op.drop_column('student_last_name')
        batch_op.drop_column('student_first_name')

    # ### end Alembic commands ###
