"""Add student table, link to certificate

Revision ID: e557b3927ac6
Revises: e0b6c8938119
Create Date: 2025-11-25 13:02:58.676742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e557b3927ac6'
down_revision = 'e0b6c8938119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('responsibility', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('year_of_employment', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('staff_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['staff_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('staff_id')
        batch_op.drop_column('year_of_employment')
        batch_op.drop_column('responsibility')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
